### ISSUE TITLE
result do not satisfied

### ISSUE THREAD

**Issue by anselleeyy** [shevek/parallelgzip#12]
I had tried ParallelGZIPOutputStream for gzip, however, the result is bigger than command-line(gzip) or GzipCompressorOutputStream.
For example, one of my origin txt file is 11G and after a gzip command to the file, it becomes to 2.4G. But your program turned the gzip file to 4.2G. I have tried change your parameter but the result is not in my expection.
I would like to ask how to config the code could make the gzip file same to the result by gzip command or GzipCompressorOutputStream by apache.
Thanks.

**Comment by simlu** [comment]
@anselleeyy Any follow up on this?

**Comment by anselleeyy** [comment]
> @anselleeyy Any follow up on this?

Yep, I had a `out.flush()` in while loop which caused this situation, when I removed that or wrote it after the whole loop, the file size is nearly the same to origin command result.
Anyway, thanks a lot.
